let apiKey =
    "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJHbGVubiIsImlhdCI6MTY3MzcwODAyNywiZXhwIjoxODMxMzg4MDI3fQ.ZcTe1E1btHdpLs3ai1p30cHT4X4wdqKRMjqc3MqvLvI";
export default apiKey;
